// src/lib/error-handling/types.ts

export enum ErrorCategory {
  Authentication = "AUTHENTICATION",
  Authorization = "AUTHORIZATION",
  Validation = "VALIDATION",
  Network = "NETWORK",
  Storage = "STORAGE",
  MediaProcessing = "MEDIA_PROCESSING",
  Geolocation = "GEOLOCATION",
  DomainVerification = "DOMAIN_VERIFICATION",
  Integrity = "INTEGRITY",
  Timeout = "TIMEOUT",
  RateLimit = "RATE_LIMIT",
  Dependency = "DEPENDENCY",
  OfflineSync = "OFFLINE_SYNC",
  NotFound = "NOT_FOUND",
  Conflict = "CONFLICT",
  Unsupported = "UNSUPPORTED",
  Internal = "INTERNAL"
}

export enum ErrorSeverity {
  Low = "LOW",
  Warning = "WARNING",
  Error = "ERROR",
  Critical = "CRITICAL"
}

export enum Recoverability {
  Recoverable = "RECOVERABLE",
  RecoverableWithUserAction = "RECOVERABLE_WITH_USER_ACTION",
  NonRecoverable = "NON_RECOVERABLE"
}

export enum ProgramDomain {
  Reforestation = "REFORESTATION",
  RiverCleanup = "RIVER_CLEANUP",
  WaterSanitationInfrastructure = "WATER_SANITATION_INFRASTRUCTURE",
  DisasterRecovery = "DISASTER_RECOVERY"
}

export enum EvidenceRole {
  Before = "BEFORE",
  During = "DURING",
  After = "AFTER",
  Verification = "VERIFICATION",
  Inspection = "INSPECTION",
  DamageAssessment = "DAMAGE_ASSESSMENT",
  StructuralSafety = "STRUCTURAL_SAFETY",
  SaplingSurvival = "SAPLING_SURVIVAL",
  EcosystemRecovery = "ECOSYSTEM_RECOVERY",
  AquaticHealth = "AQUATIC_HEALTH",
  TrashRemoval = "TRASH_REMOVAL",
  CleanupLog = "CLEANUP_LOG",
  AssetCommissioning = "ASSET_COMMISSIONING",
  Maintenance = "MAINTENANCE"
}

export enum ErrorCode {
  UNKNOWN = "UNKNOWN",
  INTERNAL = "INTERNAL",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  INVALID_INPUT = "INVALID_INPUT",
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",
  INVALID_ENUM_VALUE = "INVALID_ENUM_VALUE",
  INVALID_DATE = "INVALID_DATE",
  INVALID_TIMESTAMP = "INVALID_TIMESTAMP",
  TIMESTAMP_CONFLICT = "TIMESTAMP_CONFLICT",
  STEP_ORDER_VIOLATION = "STEP_ORDER_VIOLATION",
  DUPLICATE_RECORD = "DUPLICATE_RECORD",
  DUPLICATE_MEDIA = "DUPLICATE_MEDIA",
  DUPLICATE_CLEANUP_LOG = "DUPLICATE_CLEANUP_LOG",
  INTEGRITY_CHECK_FAILED = "INTEGRITY_CHECK_FAILED",
  CHECKSUM_MISMATCH = "CHECKSUM_MISMATCH",
  EVIDENCE_INCOMPLETE = "EVIDENCE_INCOMPLETE",
  PARTIAL_EVIDENCE_SET = "PARTIAL_EVIDENCE_SET",
  MISSING_EVIDENCE = "MISSING_EVIDENCE",
  MISSING_BEFORE_EVIDENCE = "MISSING_BEFORE_EVIDENCE",
  MISSING_AFTER_EVIDENCE = "MISSING_AFTER_EVIDENCE",
  BEFORE_AFTER_MAPPING_FAILED = "BEFORE_AFTER_MAPPING_FAILED",
  VERIFICATION_FAILED = "VERIFICATION_FAILED",
  INSUFFICIENT_EVIDENCE_QUALITY = "INSUFFICIENT_EVIDENCE_QUALITY",
  MEDIA_BLURRY = "MEDIA_BLURRY",
  MEDIA_LOW_LIGHT = "MEDIA_LOW_LIGHT",
  MEDIA_CORRUPT = "MEDIA_CORRUPT",
  MEDIA_DAMAGED = "MEDIA_DAMAGED",
  MEDIA_INACCESSIBLE = "MEDIA_INACCESSIBLE",
  MEDIA_FORMAT_UNSUPPORTED = "MEDIA_FORMAT_UNSUPPORTED",
  MEDIA_TOO_LARGE = "MEDIA_TOO_LARGE",
  MEDIA_INVALID = "MEDIA_INVALID",
  MEDIA_PROCESSING_FAILED = "MEDIA_PROCESSING_FAILED",
  MEDIA_METADATA_EXTRACTION_FAILED = "MEDIA_METADATA_EXTRACTION_FAILED",
  UPLOAD_FAILED = "UPLOAD_FAILED",
  UPLOAD_INTERRUPTED = "UPLOAD_INTERRUPTED",
  STORAGE_UNAVAILABLE = "STORAGE_UNAVAILABLE",
  STORAGE_QUOTA_EXCEEDED = "STORAGE_QUOTA_EXCEEDED",
  STORAGE_PERMISSION_DENIED = "STORAGE_PERMISSION_DENIED",
  OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND",
  NETWORK_OFFLINE = "NETWORK_OFFLINE",
  NETWORK_UNSTABLE = "NETWORK_UNSTABLE",
  NETWORK_REQUEST_FAILED = "NETWORK_REQUEST_FAILED",
  NETWORK_TIMEOUT = "NETWORK_TIMEOUT",
  DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE",
  RATE_LIMITED = "RATE_LIMITED",
  AUTH_REQUIRED = "AUTH_REQUIRED",
  AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_FORBIDDEN = "AUTH_FORBIDDEN",
  AUTH_INSUFFICIENT_ROLE = "AUTH_INSUFFICIENT_ROLE",
  AUTH_PROGRAM_ACCESS_DENIED = "AUTH_PROGRAM_ACCESS_DENIED",
  GEO_MISSING = "GEO_MISSING",
  GEO_INVALID = "GEO_INVALID",
  GPS_MISMATCH = "GPS_MISMATCH",
  GPS_DRIFT = "GPS_DRIFT",
  GEO_OUT_OF_BOUNDS = "GEO_OUT_OF_BOUNDS",
  GEO_TIMESTAMP_MISMATCH = "GEO_TIMESTAMP_MISMATCH",
  OFFLINE_CAPTURE_INVALID = "OFFLINE_CAPTURE_INVALID",
  OFFLINE_SYNC_REQUIRED = "OFFLINE_SYNC_REQUIRED",
  OFFLINE_QUEUE_CORRUPT = "OFFLINE_QUEUE_CORRUPT",
  REFORESTATION_SAPLING_SURVIVAL_UNVERIFIED = "REFORESTATION_SAPLING_SURVIVAL_UNVERIFIED",
  REFORESTATION_ECOSYSTEM_RECOVERY_UNVERIFIED = "REFORESTATION_ECOSYSTEM_RECOVERY_UNVERIFIED",
  REFORESTATION_PLOT_MISMATCH = "REFORESTATION_PLOT_MISMATCH",
  RIVER_CLEANUP_LOG_INVALID = "RIVER_CLEANUP_LOG_INVALID",
  RIVER_AQUATIC_HEALTH_UNVERIFIED = "RIVER_AQUATIC_HEALTH_UNVERIFIED",
  RIVER_TRASH_REMOVAL_UNVERIFIED = "RIVER_TRASH_REMOVAL_UNVERIFIED",
  WATER_ASSET_ID_INVALID = "WATER_ASSET_ID_INVALID",
  WATER_STRUCTURAL_INSPECTION_FAILED = "WATER_STRUCTURAL_INSPECTION_FAILED",
  WATER_SANITATION_VERIFICATION_FAILED = "WATER_SANITATION_VERIFICATION_FAILED",
  INFRASTRUCTURE_INTEGRITY_FAILED = "INFRASTRUCTURE_INTEGRITY_FAILED",
  DISASTER_DAMAGE_ASSESSMENT_INCOMPLETE = "DISASTER_DAMAGE_ASSESSMENT_INCOMPLETE",
  DISASTER_STRUCTURAL_SAFETY_UNVERIFIED = "DISASTER_STRUCTURAL_SAFETY_UNVERIFIED",
  DISASTER_LOCATION_DRIFT = "DISASTER_LOCATION_DRIFT",
  DISASTER_TIMESTAMP_CONFLICT = "DISASTER_TIMESTAMP_CONFLICT",
  CONFLICT = "CONFLICT",
  NOT_FOUND = "NOT_FOUND",
  UNSUPPORTED_PROGRAM_DOMAIN = "UNSUPPORTED_PROGRAM_DOMAIN"
}

export interface SerializedError {
  code: string;
  category: string;
  httpStatus: number;
  severity: string;
  recoverable: string;
  retryable: boolean;
  message: string;
  userMessage: string;
  details?: Record<string, unknown>;
  context?: Record<string, unknown>;
  stack?: string;
}

export type Result<T> =
  | { ok: true; value: T }
  | { ok: false; error: import("./app-error").AppError };

export function ok<T>(value: T): Result<T> {
  return { ok: true, value };
}

export function err(error: import("./app-error").AppError): Result<never> {
  return { ok: false, error };
}
